capitals_dict = {
    'Alabama': ('Montgomery',  "Montgomery.gif"),
    'Alaska': ('Juneau',  "Juneau.gif"),
    'Arizona': ('Phoenix',  "Phoenix.gif"),
    'Arkansas': ('Little Rock',  "Little Rock.gif"),
    'California': ('Sacramento',  "Sacramento.gif"),
    'Colorado': ('Denver',  "Denver.gif"),
    'Connecticut': ('Hartford',  "Hartford.gif"),
    'Delaware': ('Dover',  "Dover.gif"),
    'Florida': ('Tallahassee',  "Tallahassee.gif"), 
    'Georgia': ('Atlanta',  "Atlanta.gif"),
    'Hawaii': ('Honolulu',  "Honolulu.gif"),
    'Idaho': ('Boise',  "Boise.gif"),
    'Illinois': ('Springfield',  "Springfield.gif"),
    'Indiana': ('Indianapolis',  "Indianapolis.gif"),
    'Iowa': ('Des Moines',  "Des Moines.gif"),
    'Kansas': ('Topeka',  "Topeka.gif"),
    'Kentucky': ('Frankfort',  "Frankfort.gif"),
    'Louisiana': ('Baton Rouge',  "Baton Rouge.gif"),
    'Maine': ('Augusta',  "Augusta.gif"),
    'Maryland': ('Annapolis',  "Annapolis.gif"),
    'Massachusetts': ('Boston',  "Boston.gif"),
    'Michigan': ('Lansing',  "Lansing.gif"),
    'Minnesota': ('Saint Paul',  "St. Paul.gif"),
    'Mississippi': ('Jackson',  "Jackson.gif"),
    'Missouri': ('Jefferson City',  "Jefferson City.gif"),
    'Montana': ('Helena',  "Helena.gif"),
    'Nebraska': ('Lincoln',  "Lincoln.gif"),
    'Nevada': ('Carson City',  "Carson City.gif"),
    'New Hampshire': ('Concord',  "Concord.gif"),
    'New Jersey': ('Trenton',  "Trenton.gif"),
    'New Mexico': ('Santa Fe',  "Santa Fe.gif"),
    'New York': ('Albany',  "Albany.gif"),
    'North Carolina': ('Raleigh',  "Raleigh.gif"), 
    'North Dakota': ('Bismarck',  "Bismarck.gif"),
    'Ohio': ('Columbus',  "Columbus.gif"),
    'Oklahoma': ('Oklahoma City',  "Oklahoma City.gif"),
    'Oregon': ('Salem',  "Salem.gif"),
    'Pennsylvania': ('Harrisburg',  "Harrisburg.gif"),
    'Rhode Island': ('Providence',  "Providence.gif"),
    'South Carolina': ('Columbia',  "Columbia.gif"), 
    'South Dakota': ('Pierre',  "Pierre.gif"),
    'Tennessee': ('Nashville',  "Nashville.gif"),
    'Texas': ('Austin',  "Austin.gif"),
    'Utah': ('Salt Lake City',  "Salt Lake City.gif"),
    'Vermont': ('Montpelier',  "Montpelier.gif"),
    'Virginia': ('Richmond',  "Richmond.gif"),
    'Washington': ('Olympia',  "Olympia.gif"),
    'West Virginia': ('Charleston',  "Charleston.gif"),
    'Wisconsin': ('Madison',  "Madison.gif"),
    'Wyoming': ('Cheyenne',  "Cheyenne.gif"),
} 